[project]
name = "alphagenome-ft-mpra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.3",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "requests>=2.32.5",
]
